GET http://brettspill.localhost:8008/

###

POST http://brettspill.localhost:8008/lobby/register/
content-type: application/json

{
  "username": "sampleuser",
  "email": "tewst@testss.com",
  "password": "Testpassord123",
  "password2": "Testpassord123"
}

###

POST http://brettspill.localhost:8008/lobby/login/
content-type: application/json

{
  "username": "sampleuser",
  "password": "Testpassord123"
}

###
GET http://brettspill.localhost:8008/lobby/spiller/1

###

POST http://brettspill.localhost:8008/lobby/spill/
content-type: application/json

{
  "spill_navn": "Testspill",
  "spill_type": "MPOL"
}

### Login, 

