version: '3.7'

services:
  brettspill:
    image: brettspill-py
    container_name: brettspill
    restart: "no"
    depends_on:
      - "db"
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn brettspill_py.asgi:application --host 0.0.0.0 --port 8000'
    expose:
      - 8000
    env_file:
      - ./env/brettspill.env
    volumes:
      - ./app:/app
    networks:
      - brettspill-backend
      - brettspill-frontend
    labels: # new
      - "traefik.enable=true"
      - "traefik.http.routers.brettspill.rule=Host(`brettspill.localhost`)"
      - "traefik.http.routers.brettspill.tls=true"
      - "traefik.docker.network=brettspill_frontend"
    
  db:
    image: postgres:13.3-alpine
    container_name: brettpill_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ../brettspill-db/postgres.conf:/etc/postgresql/postgresql.conf
      - pgdata:/var/lib/postgresql/data
    networks:
      - brettspill-backend
    env_file:
      - ./env/database.env # configure postgres

  pgAdmin:
    image: dpage/pgadmin4:6.12
    container_name: dev-pgadmin
    restart: always
    environment: 
      - PGADMIN_DEFAULT_EMAIL=espen.holtebu@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    volumes:
      - pgadmin_vol:/var/lib/pgadmin
    networks:
      - brettspill-backend
      - brettspill-frontend
    expose:
      - 80
    labels: # new
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.localhost`)"

  traefik: # new
    image: traefik:v2.8.1
    container_name: "traefik"
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.traefik=true"
    networks:
      - brettspill-backend
    ports:  #"ute:inne"
      - 80:80
      - 8001:8000
      - 8080:8080
      - 443:443
    volumes:
      - "./app/.certs/:/etc/certs:ro"
      - "./traefik.dev.yml:/etc/traefik/traefik.yml:ro"
      - "./traefik.routes.dev.yml:/etc/traefik/config.yml:ro"
      - "/mnt/wsl/shared-docker/docker.sock:/var/run/docker.sock:ro"

networks:
  brettspill-frontend:
    driver: bridge
  brettspill-backend:
    driver: bridge

volumes:
  pgadmin_vol:
  pgdata: