version: '3.7'

volumes:
  pgdata:

services:
  db:
    image: postgres:13.3-alpine
    container_name: brettpill_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./brettspill_db/postgres.conf:/etc/postgresql/postgresql.conf
      - pgdata:/var/lib/postgresql/data
    networks:
      - brettspill-backend
    env_file:
      - ./brettspill_db/database.env # configure postgres

  adminer:
    image: adminer
    restart: always
    networks:
      - brettspill-backend
      - brettspill-frontend
    ports:
      - 8080:8080

networks:
  brettspill-frontend:
    driver: bridge
  brettspill-backend:
    driver: bridge