version: '3.7'

services:
  brettspill:
    image: brettspill-py
    container_name: brettspill
    restart: "no"
    depends_on:
      - "db"
    build: .
    command:  bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    # bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn brettspill_py.asgi:application --host 0.0.0.0 --port 8000 --reload'
    expose:
      - 8000
    env_file:
      - ./env/brettspill.env
    volumes:
      - ./app:/app
    networks:
      - bsp_backend
      - bsp_frontend
    labels: # new
      - "traefik.enable=true"
      # docker inspect <container_id>
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.brettspill.rule=Host(`brettspill.localhost`)"
      - "traefik.http.routers.brettspill.tls=true"
    
  db:
    image: postgres:13.3-alpine
    container_name: brettpill_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ../brettspill-db/postgres.conf:/etc/postgresql/postgresql.conf
      - pgdata:/var/lib/postgresql/data
    networks:
      - bsp_backend
    env_file:
      - ./env/database.env # configure postgres

  pgAdmin:
    image: dpage/pgadmin4:8.1
    container_name: dev-pgadmin
    restart: always
    environment: 
      - PGADMIN_DEFAULT_EMAIL=espen.holtebu@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    volumes:
      - pgadmin_vol:/var/lib/pgadmin
    networks:
      - bsp_backend
      - bsp_frontend
    expose:
      - 80
    labels: # new
      - "traefik.enable=true"
      # docker inspect <container_id>
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.localhost`)"
      - "traefik.http.routers.pgadmin.tls=true"

  traefik: # new
    image: traefik:v2.9.8
    container_name: "traefik"
    networks:
      - bsp_frontend
    ports:  #"ute:inne"
      - 80:80
      - 443:443
    volumes:
      - "./app/.certs/:/etc/certs:ro"
      # At startup, Traefik searches for static configuration in a file named traefik.yml (or traefik.yaml or traefik.toml) in /etc/traefik/
      - "./traefik.dev.yml:/etc/traefik/traefik.yml:ro"
      - "./traefik.routes.dev.yml:/etc/traefik/config.yml:ro"
      - "/mnt/wsl/shared-docker/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.docker.localhost`)"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"

networks:
  bsp_frontend:
    name: frontend
    driver: bridge
  bsp_backend:
    name: backend
    driver: bridge

volumes:
  pgadmin_vol:
  pgdata: