version: '3.7'

volumes:
  pgdata:

services:
  db:
    image: postgres:13.3-alpine
    container_name: brettpill_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./brettspill_db/postgres.conf:/etc/postgresql/postgresql.conf
      - pgdata:/var/lib/postgresql/data
    networks:
      - brettspill-backend
    env_file:
      - ./brettspill_db/database.env # configure postgres

  pgAdmin:
    image: dpage/pgadmin4
    container_name: dev-pgadmin
    restart: always
    environment: 
      - PGADMIN_DEFAULT_EMAIL=espen.holtebu@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    networks:
      - brettspill-backend
      - brettspill-frontend
    ports:
      - "80:80"

networks:
  brettspill-frontend:
    driver: bridge
  brettspill-backend:
    driver: bridge