# traefik.dev.toml
global:
  sendAnonymousUsage: false
# listen on port 80
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

# Traefik dashboard
api:
  dashboard: true
  insecure: true

log:
  level: "DEBUG"
  format: common

accessLog:

# containers are not discovered automatically
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

  file:
    filename: /etc/traefik/config.yml
    watch: true