# traefik.dev.toml
global:
  sendAnonymousUsage: true
# listen on port 80
entryPoints:
  web:
    address: ":80"

# Traefik dashboard over http
api:
  insecure: true

log:
  level: "DEBUG"

accessLog:

# containers are not discovered automatically
providers:
  docker:
    exposedByDefault: false