# traefik.dev.toml
global:
  sendAnonymousUsage: true
# listen on port 80
entryPoints:
  traefik:
    address: ":8080"
  web:
    address: ":80"

# Traefik dashboard
api:
  dashboard: true

log:
  level: "DEBUG"
  format: common

accessLog:
  filePath: /etc/traefik/accesslog/access.log
  format: json


providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    # containers are not discovered automatically
    exposedByDefault: false