# Generated by Django 4.0.6 on 2022-07-27 10:40

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spill_navn', models.CharField(help_text='Navn for å kjenne igjen spillet senere.', max_length=25)),
                ('spill_type', models.CharField(choices=[('MPOL', 'Monopol')], default='MPOL', help_text='Type spill', max_length=4)),
                ('start_tid', models.DateTimeField()),
                ('slutt_tid', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Spiller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpillerISpill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farge', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('plassering', models.SmallIntegerField()),
                ('spill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobby.spill')),
                ('spiller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobby.spiller')),
            ],
        ),
        migrations.AddField(
            model_name='spill',
            name='spillere',
            field=models.ManyToManyField(through='lobby.SpillerISpill', to='lobby.spiller'),
        ),
        migrations.AddField(
            model_name='spill',
            name='vert',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
