# Generated by Django 4.0.6 on 2022-12-23 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spillerispill',
            unique_together={('spiller', 'spill')},
        ),
    ]
