# Generated by Django 4.0.6 on 2023-02-17 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0004_spillerispill_vert'),
    ]

    operations = [
        migrations.AddField(
            model_name='spill',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
