# Generated by Django 4.0.6 on 2023-02-17 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0005_spill_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spill',
            old_name='created',
            new_name='opprettet_tid',
        ),
    ]
