# Generated by Django 4.0.6 on 2023-02-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0006_rename_created_spill_opprettet_tid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spill',
            name='slutt_tid',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spill',
            name='start_tid',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
